import { } from 'react'
import cicero from './assets/cicero.jpg'

function About(){
    return(
        <>
        <img src={cicero} alt="senador cicero" />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vulputate sem eget nulla tincidunt lobortis. In sit amet lorem ipsum. Curabitur elementum eleifend elit sed laoreet. In ac est rhoncus, rhoncus nibh sed, molestie libero. Aenean condimentum tempus orci, ut consequat odio bibendum quis. Sed sagittis porta bibendum. Donec posuere maximus justo at aliquam. Mauris in aliquet sapien, at ornare diam. Aenean maximus diam vel turpis rhoncus, non convallis lorem vehicula. Duis pretium ipsum nulla, non convallis ligula porttitor eget. Nunc dapibus nisi ante, at pellentesque nisl finibus quis. Phasellus vitae aliquam mi, eget placerat nibh. Nulla ornare turpis id risus fermentum, non tempor quam ullamcorper. Nunc in sagittis justo. Aenean quam leo, vestibulum sed imperdiet et, tempor quis nibh. Mauris tristique purus vitae mi feugiat, id sagittis neque pulvinar. In at egestas ligula. Vivamus eu mauris pharetra nisl porta imperdiet id non purus. Nulla leo mi, ornare sit amet lorem ut, bibendum lobortis nibh. Proin tincidunt ultricies vulputate. Integer sed euismod risus, quis congue neque. Aenean non ornare lorem, quis pharetra nisl. Aliquam erat volutpat. Morbi mattis, tellus a auctor eleifend, nisi diam tempor turpis, ut porttitor arcu enim vitae ante. Pellentesque ornare ultrices massa ac iaculis. Ut finibus convallis urna, ac tempor ipsum molestie in. Nullam iaculis leo sem, vitae congue lectus ultrices finibus. Praesent vestibulum mi id sem viverra cursus. Mauris ac sodales magna. Mauris pharetra sem eget neque sagittis elementum. Vestibulum at suscipit justo. In id consequat lectus. Donec vitae elit vulputate, venenatis lectus et, tincidunt magna. Ut eu convallis ipsum. Maecenas magna nibh, tincidunt nec porttitor eu, mollis vel leo. Maecenas sodales pretium eros ut luctus. Duis ac ligula sodales, eleifend lacus quis, convallis est. In et varius libero. Donec sit amet sem vel nisl hendrerit mattis. Aliquam nec commodo lorem. Duis accumsan at sapien at laoreet. In nunc orci, malesuada ac nunc sit amet, pellentesque faucibus mauris. Fusce tempus vehicula odio non sagittis. Sed et nisl eu quam euismod viverra. Donec est risus, tincidunt ac quam quis, viverra tincidunt mi. Mauris porta dictum magna sit amet convallis. Nullam mattis nulla id enim pellentesque, ut interdum elit lacinia. Aliquam vel diam luctus, consequat quam sed, laoreet sapien. Integer interdum, elit eu sodales blandit, nibh massa mollis quam, at scelerisque ex tortor a nunc. Nulla ac ex nec risus gravida efficitur. In rutrum neque imperdiet ipsum bibendum, vitae accumsan metus accumsan. Aliquam fermentum tempus ante sit amet tincidunt. Morbi fringilla ac nunc eu semper. Ut orci lacus, iaculis id varius at, semper non enim. Sed luctus vestibulum accumsan. </p>
        </>
    )
}
export default About